module.exports = {
  type: 'postgres',
  host: 'localhost',
  port: '5432',
  username: 'woo_bottle',
  password: '0000',
  database: 'bus_development',
  ssl: false,
  synchronize: true,
  logging: false,
  entities: ['src/**/*.entity.ts'],
  seeds: ['src/db/seeds/**/*.seed.ts'],
  factories: ['src/db/factories/**/*.factory.ts'],
  migrations: ['src/db/migration/**/*.ts'],
  subscribers: ['src/subscriber/**/*.ts'],
  cli: {
    migrationsDir: 'src/db/migration',
    subscribersDir: 'src/db/subscriber',
  },
};
