module.exports = {
  type: 'postgres',
  host: process.env.DB_HOST || 'localhost',
  port: '5432',
  username: process.env.DB_USERNAME || 'woo_bottle',
  password: process.env.DB_PASSWORD || '0000',
  database: process.env.DB_DATABASE || 'bus_development',
  ssl: false,
  synchronize: false,
  logging: false,
  entities: ['dist/src/**/*.entity.js'],
  seeds: ['dist/src/db/seeds/*.seed.js'],
  factories: ['dist/src/db/factories/*.factory.js'],
  migrations: ['src/db/migration/**/*.ts'],
  subscribers: ['src/subscriber/**/*.ts'],
  cli: {
    migrationsDir: 'src/db/migration',
    subscribersDir: 'src/db/subscriber',
  },
};
