/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-2",
    "aws_cognito_identity_pool_id": "ap-northeast-2:851776a1-bb82-4173-ae45-81c346b4e759",
    "aws_cognito_region": "ap-northeast-2",
    "aws_user_pools_id": "ap-northeast-2_DJbbNgcV8",
    "aws_user_pools_web_client_id": "7mulk7f2bedvogk65p0edji3fp",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://3bhj6nlgjvd6ljhmzx2afr3b2u.appsync-api.ap-northeast-2.amazonaws.com/graphql",
    "aws_appsync_region": "ap-northeast-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
