/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-2",
    // "aws_cognito_identity_pool_id": "ap-northeast-2:8c612177-28c0-4574-b45e-eaa9e35381d5",
    "aws_cognito_region": "ap-northeast-2",
    "aws_user_pools_id": "ap-northeast-2_A7xpHDFAK",
    "aws_user_pools_web_client_id": "79307ehbtr2o3ln1ip8dcb9v6p",
    "oauth": {}
};


export default awsmobile;
